### ISSUE TITLE
Allow multiple catalog categories?

### ISSUE THREAD

**Issue by varshith93** [ivan-betev/sn-catalog-item-explorer#1]
In the next iteration, can you please allow multiple catalog categories?

**Comment by ivan-betev** [comment]
Hi @varshith93 , 

thank you for your feedback, I've now returned from the New Year holidays and will be able to process it.

Regards, Ivan

**Comment by ivan-betev** [comment]
Hi @varshith93 ,

The purpose of the widget is to ultimately have a single required selection. What would be the use case for allowing multiple category selections?

Regards, Ivan

**Comment by varshith93** [comment]
Hi @ivan-betev, showing multiple catalog selections aims to increase visibility. Let us take our company as an example. We are a franchise company, and our employee submits Catalog items on behalf of Franchisees. We have catalog items that are separated for employees and Franchisees. In this case, allowing multiple catalog categories will help our employees see both Catalog items in the same widget.

**Comment by ivan-betev** [comment]
Hi @varshith93 , do you need a possibility to connect multiple catalogs to the widget? Is that correct? If yes, I've already added this feature, you can specify catalogs in the options.

**Comment by varshith93** [comment]
@ivan-betev, Thank you for enabling the option to select multiple catalogs and keeping the widget up-to-date. However, I have noticed that if a catalog item is associated with multiple catalogs, it does not appear in the widget. For instance, if I select "Hardware" and "Onboarding" catalogs for a catalog item called "Laptop Request," the item does not show up in the widget. It only seems to work when a catalog item is associated with a single catalog.

**Comment by ivan-betev** [comment]
Hey @varshith93 ,

Have you selected the catalogs in the widget options? I've just tested it with items that are associated with multiple catalogs, and see no issues, no matter how many catalogs are connected.

Could you provide me with more details? Can you reproduce it in PDI?

Regards, Ivan

**Comment by varshith93** [comment]
@ivan-betev  you right! I checked in PDI, and it's working fine. I am not sure what is happening with our instance. I will reach out to you via LinkedIn if I have any questions. Thanks Ivan! I truly appreciate your support on this.
